import { DecisionAnalysis } from '../types/decision.types'

export function exportDecisionMemo(
  analysis: DecisionAnalysis,
  context?: string,
  rationale?: string
) {
  const dateStr = new Date().toISOString().split('T')[0]
  const content = `# 🧭 ReasonLens: Executive Decision Memo
**Google Labs Socratic Thinking Experiment**
*Generated: ${dateStr} • Model: Gemini 2.5 Flash • Tool: Google Antigravity*

> **The Non-Decision Pledge:**
> *"ReasonLens never decides for you. We stress-test your logic so you decide with conviction."*

---

## 1. Decision Framing
${context ? `- **Decision Context:** ${context}\n` : ''}${rationale ? `- **Proposed Rationale:** ${rationale}\n` : ''}- **Executive Synopsis:** ${analysis.summary}
- **Logic Clarity Score:** ${analysis.clarityScore} / 100

---

## 2. Unmasked Fragile Assumptions
${analysis.unstatedAssumptions
  .map(
    (a, i) => `### Assumption #${i + 1}: ${a.assumption}
- **Vulnerability Level:** ${a.vulnerability}
- **Fragility Analysis:** ${a.reasoning}
`
  )
  .join('\n')}

---

## 3. 12-Month Prospective Pre-Mortem
${analysis.preMortemScenarios
  .map(
    (s, i) => `### Failure Scenario #${i + 1}
- **What Went Wrong:** ${s.whatWentWrong}
- **Root Catalyst Trigger:** ${s.catalyst}
`
  )
  .join('\n')}

---

## 4. Piercing Socratic Inquiries
${analysis.socraticQuestions
  .map(
    (q, i) => `${i + 1}. **"${q.question}"**
   - *Cognitive / Strategic Angle:* ${q.reasoningAngle}`
  )
  .join('\n\n')}

---
*Generated by ReasonLens • Google Labs Experimental Prototype*
`

  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.setAttribute('download', `ReasonLens_Decision_Memo_${dateStr}.md`)
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
